name: bioinfosoft
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - jupyterlab=3
    - numpy
    - scipy
    - pandas
    - matplotlib
    - requests
    - python-dotenv
    - lxml
    - biopython
    - xmltodict
    - dash
    - plotly
    - pip:
      - dash==0.35.1
      - dash-html-components==0.13.4
      - dash-core-components==0.42.1
      - dash-table==3.1.11
    # download data files
    - tqdm
    # linters and more
    - pylint
    - pycodestyle
    - pydocstyle
    - black
    - ruff
    - pip:
        - watermark

